--------------------------------------------------------------
 --  Copyright (c) 2012-2025 Anlogic Inc. --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	C:/Users/Lenovo/Desktop/selftimekeep/al_ip/BRAM256K_0.vhd
 -- Date	:	2026 04 17
 -- TD version	:	6.2.178840
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY ef2_macro;
	USE ef2_macro.EF2_COMPONENTS.all;

ENTITY BRAM256K_0 IS
PORT (
	doa	: OUT STD_LOGIC_VECTOR(31 DOWNTO 0);

	dia	: IN STD_LOGIC_VECTOR(31 DOWNTO 0);
	cea	: IN STD_LOGIC;
	clka	: IN STD_LOGIC;
	wea	: IN STD_LOGIC;
	addra	: IN STD_LOGIC_VECTOR(12 DOWNTO 0);
	weabyte	: IN STD_LOGIC_VECTOR(3 DOWNTO 0);

	dob	: OUT STD_LOGIC_VECTOR(31 DOWNTO 0);

	dib	: IN STD_LOGIC_VECTOR(31 DOWNTO 0);
	ceb	: IN STD_LOGIC;
	clkb	: IN STD_LOGIC;
	web	: IN STD_LOGIC;
	addrb	: IN STD_LOGIC_VECTOR(12 DOWNTO 0);
	webbyte	: IN STD_LOGIC_VECTOR(3 DOWNTO 0)
	);
END BRAM256K_0;

ARCHITECTURE struct OF BRAM256K_0 IS

	BEGIN
	bram256k : EF2_PHY_BRAM256K
		GENERIC MAP (
			MODE			=> "DP",
			REGMODE_A	=> "NOREG",
			WRITEMODE_A	=> "NORMAL",
			REGMODE_B	=> "NOREG",
			WRITEMODE_B	=> "NORMAL",
			INIT_FILE	=> "NONE"
		)
		PORT MAP (
			doa	=> doa,
			dia	=> dia,
			cea	=> cea,
			ocea	=> '0',
			clka	=> clka,
			wea	=> wea,
			rsta	=> '0',
			addra	=> addra,
			weabyte	=> weabyte,

			dob	=> dob,
			dib	=> dib,
			ceb	=> ceb,
			oceb	=> '0',
			clkb	=> clkb,
			web	=> web,
			rstb	=> '0',
			addrb	=> addrb,
			webbyte	=> webbyte
		);

END struct;
