/************************************************************\
 **  Copyright (c) 2012-2025 Anlogic Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	C:/Users/Lenovo/Desktop/selftimekeep/al_ip/BRAM256K_0.v
 ** Date	:	2026 04 17
 ** TD version	:	6.2.178840
************************************************************/

`timescale 1ns / 1ps

module BRAM256K_0 ( doa,dob,dia,cea,clka,wea,addra,weabyte,
			dib,ceb,clkb,web,addrb,webbyte );
	output 		[31:0] doa;
	output 		[31:0] dob;

	input  		[31:0] dia;
	input  		cea;
	input  		clka;
	input  		wea;
	input  		[12:0] addra;
	input  		[3:0] weabyte;

	input  		[31:0] dib;
	input  		ceb;
	input  		clkb;
	input  		web;
	input  		[12:0] addrb;
	input  		[3:0] webbyte;


		EF2_PHY_BRAM256K #(
		.MODE("DP"),
		.REGMODE_A("NOREG"),
		.REGMODE_B("NOREG"),
		.WRITEMODE_A("NORMAL"),
		.WRITEMODE_B("NORMAL"),
		.INIT_FILE("NONE"))

		inst (
		.dia(dia),
		.dib(dib),
		.cea(cea),
		.ceb(ceb),
		.ocea(1'b0),
		.oceb(1'b0),
		.clka(clka),
		.clkb(clkb),
		.wea(wea),
		.web(web),
		.rsta(1'b0),
		.rstb(1'b0),
		.addra(addra),
		.addrb(addrb),
		.weabyte(weabyte),
		.webbyte(webbyte),
		.doa(doa),
		.dob(dob));

endmodule