/************************************************************\
 **  Copyright (c) 2012-2025 Anlogic Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	C:/Users/Lenovo/Desktop/selftimekeep/al_ip/FIFO_write.v
 ** Date	:	2026 04 15
 ** TD version	:	6.2.178840
************************************************************/

`timescale 1ns / 1ps

module FIFO_write (
	rst,
	di, clk, we,
	do, re,
	empty_flag,
	full_flag, afull_flag 
);

	input rst;
	input [31:0] di;
	input clk, we;
	input re;

	output [63:0] do;
	output empty_flag;
	output full_flag, afull_flag;

EF2_LOGIC_FIFO #(
 	.DATA_WIDTH_W(32),
	.DATA_WIDTH_R(64),
	.DATA_DEPTH_W(1024),
	.DATA_DEPTH_R(512),
	.ENDIAN("BIG"),
	.RESETMODE("SYNC"),
	.E(0),
	.F(1024),
	.ASYNC_RESET_RELEASE("SYNC"),
	.AF(1018))
fifo_inst(
	.rst(rst),
	.di(di),
	.clkw(clk),
	.we(we),
	.csw(3'b111),
	.do(do),
	.clkr(clk),
	.re(re),
	.csr(3'b111),
	.ore(1'b0),
	.empty_flag(empty_flag),
	.aempty_flag(),
	.full_flag(full_flag),
	.afull_flag(afull_flag)

);

endmodule