/************************************************************\
 **  Copyright (c) 2012-2025 Anlogic Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	E:/fjlwork/selftimekeep/al_ip/FIFO_0.v
 ** Date	:	2026 01 21
 ** TD version	:	6.2.178840
************************************************************/

`timescale 1ns / 1ps

module FIFO_0(dout, empty_flag, full_flag, fifo_wrpointer, fifo_rdpointer,
	wrst, rrst, di, clk, we, re);

    input                         wrst;
    input                         rrst;
    input         [7:0]           di;
    input                         clk;
    input                         we;
    input                         re;
    output        [7:0]           dout;
    output                        empty_flag;
    output                        full_flag;
    output       [13:0]           fifo_wrpointer;
    output       [13:0]           fifo_rdpointer;
    PH1_LOGIC_FIFO #(
        .DATA_WIDTH(8),
        .ADDR_WIDTH(14),
        .REGMODE_R("OUTREG"),
        .FIRSTWRITE_RD("DISABLE"),
        .ASYNC_RESET_RELEASE("SYNC"),
        .CLKMODE("SYNC"),
        .SSROVERCE("DISABLE"),
        .ECC_ENCODE("DISABLE"),
        .ECC_DECODE("DISABLE"))
    fifo_inst (
		.wrst(wrst),
		.rrst(rrst),
		.di(di),
		.clkw(clk),
		.we(we),
		.csw(3'b111),
		.dout(dout),
		.clkr(clk),
		.re(re),
		.csr(3'b111),
		.empty_flag(empty_flag),
		.aempty_flag(),
		.full_flag(full_flag),
		.afull_flag(),
		.ecc_sbiterr(),
		.ecc_dbiterr(),
		.fifo_wrpointer(fifo_wrpointer),
		.fifo_rdpointer(fifo_rdpointer)
		);
endmodule
