--------------------------------------------------------------
 --  Copyright (c) 2012-2025 Anlogic Inc. --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	C:/Users/Lenovo/Desktop/selftimekeep/al_ip/FIFO_write.vhd
 -- Date	:	2026 04 15
 -- TD version	:	6.2.178840
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY ef2_macro;
	USE ef2_macro.EF2_COMPONENTS.all;

ENTITY FIFO_write IS
PORT (
	di	: IN STD_LOGIC_VECTOR(31 DOWNTO 0);

	rst	: IN STD_LOGIC;
	clk	: IN STD_LOGIC;
	we	: IN STD_LOGIC;
	re	: IN STD_LOGIC;
	do	: OUT STD_LOGIC_VECTOR(63 DOWNTO 0);
	empty_flag		: OUT STD_LOGIC;
	full_flag		: OUT STD_LOGIC;
	afull_flag		: OUT STD_LOGIC
	);
END FIFO_write;

ARCHITECTURE struct OF FIFO_write IS

	BEGIN
	fifo_inst : EF2_LOGIC_FIFO
		GENERIC MAP (
			DATA_WIDTH_W			=> 32,
			DATA_DEPTH_W			=> 1024,
			DATA_WIDTH_R			=> 64,
			DATA_DEPTH_R			=> 512,
			ENDIAN				=> "BIG",
			RESETMODE			=> "SYNC",
			REGMODE_R			=> "NOREG",
			E					=> 0,
			F					=> 1024,
			ASYNC_RESET_RELEASE	=> "SYNC",
			AF					=> 1018
		)
		PORT MAP (
			rst	=> rst,
			di	=> di,
			clkw	=> clk,
			we	=> we,
			csw	=> "111",
			clkr	=> clk,
			ore	=> '0',
			re	=> re,
			csr	=> "111",
			do	=> do,
			empty_flag	=> empty_flag,
			aempty_flag	=> OPEN,
			full_flag	=> full_flag,
			afull_flag	=> afull_flag
		);

END struct;
