--------------------------------------------------------------
 --  Copyright (c) 2012-2025 Anlogic Inc. --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	E:/fjlwork/selftimekeep/al_ip/FIFO_0.vhd
 -- Date	:	2026 01 21
 -- TD version	:	6.2.178840
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY ph1_macro;
	USE ph1_macro.PH1_COMPONENTS.all;

ENTITY FIFO_0 IS
PORT (
    wrst	: IN STD_LOGIC;
    rrst	: IN STD_LOGIC;
    di	: IN STD_LOGIC_VECTOR(7 DOWNTO 0);

    clk	: IN STD_LOGIC;
    we	: IN STD_LOGIC;
    re	: IN STD_LOGIC;
    dout	: OUT STD_LOGIC_VECTOR(7 DOWNTO 0);

    empty_flag	: OUT STD_LOGIC;
    full_flag	: OUT STD_LOGIC;
    fifo_wrpointer	: OUT STD_LOGIC_VECTOR(13 DOWNTO 0);

    fifo_rdpointer	: OUT STD_LOGIC_VECTOR(13 DOWNTO 0)

);
END FIFO_0;

ARCHITECTURE struct OF FIFO_0 IS

    BEGIN
        fifo_inst : PH1_LOGIC_FIFO
            GENERIC MAP (
                DATA_WIDTH	=> 8,
                ADDR_WIDTH	=> 14,
                REGMODE_R	=> "OUTREG",
                FIRSTWRITE_RD	=> "DISABLE",
                ASYNC_RESET_RELEASE	=> "SYNC",
                CLKMODE	=> "SYNC",
                SSROVERCE	=> "DISABLE",
                ECC_ENCODE	=> "DISABLE",
                ECC_DECODE	=> "DISABLE"
            )
            PORT MAP (
			wrst	=> wrst,
			rrst	=> rrst,
			di	=> di,
			clkw	=> clk,
			we	=> we,
			csw	=> "111",
			clkr	=> clk,
			re	=> re,
			csr	=> "111",
			dout	=> dout,
			empty_flag	=> empty_flag,
			aempty_flag	=> OPEN,
			full_flag	=> full_flag,
			afull_flag	=> OPEN,
			ecc_sbiterr	=> OPEN,
			ecc_dbiterr	=> OPEN,
			fifo_wrpointer	=> fifo_wrpointer,
			fifo_rdpointer	=> fifo_rdpointer
            );

END struct;
